services:
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data

volumes:
  redis-data: { }