services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_ADDR: 'redis:6379'
    ports:
      - '8080:8080'
    restart: unless-stopped

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 1s
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data

volumes:
  redis-data: { }